# -*- coding: utf-8 -*-
import json, re, sys

CAT = "C:/Users/sebas/Documents/r3set/apps/mobile/scripts/data/hevy-catalog.json"
OUT = "C:/Users/sebas/Documents/r3set/apps/mobile/scripts/data/i18n-names.json"
cat = json.load(open(CAT, encoding="utf-8"))

# Equipo entre paréntesis -> español (coach argentino)
EQUIP = {
    "Barbell": "Barra", "Dumbbell": "Mancuerna", "Cable": "Polea", "Machine": "Máquina",
    "Smith Machine": "Máquina Smith", "Kettlebell": "Kettlebell", "Band": "Banda",
    "Bodyweight": "Peso Corporal", "Suspension": "TRX", "Weighted": "con Peso",
    "Assisted": "Asistida", "Machine Plates": "Máquina (Discos)", "Trap bar": "Barra Hexagonal",
    "Smith": "Smith", "Down to up": "de abajo hacia arriba", "Up to down": "de arriba hacia abajo",
}

# Movimiento base -> español (coach profesional argentino)
BASE = {
    "21s Bicep Curl": "Curl de Bíceps 21s",
    "Ab Scissors": "Tijeras Abdominales",
    "Ab Wheel": "Rueda Abdominal",
    "Aerobics": "Aeróbic",
    "Air Bike": "Bicicleta de Aire",
    "Arnold Press": "Press Arnold",
    "Around The World": "Círculos con Mancuernas",
    "Assisted Pistol Squats": "Sentadilla Pistol Asistida",
    "Back Extension": "Extensión Lumbar",
    "Ball Slams": "Golpes con Balón",
    "Band Pullaparts": "Aperturas con Banda",
    "Battle Ropes": "Sogas de Batalla",
    "Behind the Back Bicep Wrist Curl": "Curl de Muñeca por Detrás de la Espalda",
    "Bench Dip": "Fondos en Banco",
    "Bench Press": "Press de Banca",
    "Bench Press - Close Grip": "Press de Banca Agarre Cerrado",
    "Bench Press - Wide Grip": "Press de Banca Agarre Ancho",
    "Bent Over Row": "Remo Inclinado",
    "Bicep Curl": "Curl de Bíceps",
    "Bicycle Crunch": "Abdominal Bicicleta",
    "Bicycle Crunch Raised Legs": "Abdominal Bicicleta con Piernas Elevadas",
    "Bird Dog": "Bird Dog",
    "Box Jump": "Salto al Cajón",
    "Box Squat": "Sentadilla al Cajón",
    "Boxing": "Boxeo",
    "Bulgarian Split Squat": "Sentadilla Búlgara",
    "Burpee": "Burpee",
    "Burpee Over the Bar": "Burpee sobre la Barra",
    "Butterfly": "Contractor de Pecho",
    "Cable Core Palloff Press": "Press Pallof en Polea",
    "Cable Crunch": "Abdominal en Polea",
    "Cable Fly Crossovers": "Cruces en Polea",
    "Cable Pull Through": "Pull Through en Polea",
    "Cable Twist": "Giro en Polea",
    "Calf Extension": "Extensión de Gemelos",
    "Calf Press": "Press de Gemelos",
    "Chest Dip": "Fondos de Pecho",
    "Chest Fly": "Aperturas de Pecho",
    "Chest Press": "Press de Pecho",
    "Chest Supported Incline Row": "Remo Inclinado con Apoyo de Pecho",
    "Chest Supported Reverse Fly": "Aperturas Invertidas con Apoyo de Pecho",
    "Chest Supported Y Raise": "Elevación en Y con Apoyo de Pecho",
    "Chin Up": "Dominada Supina",
    "Clamshell": "Almeja",
    "Clap Push Ups": "Flexiones con Aplauso",
    "Clean": "Cargada",
    "Clean Pull": "Tirón de Cargada",
    "Clean and Jerk": "Cargada y Envión",
    "Clean and Press": "Cargada y Press",
    "Climbing": "Escalada",
    "Concentration Curl": "Curl Concentrado",
    "Cross Body Hammer Curl": "Curl Martillo Cruzado",
    "Crunch": "Abdominal Crunch",
    "Curtsy Lunge": "Zancada Cruzada",
    "Cycling": "Ciclismo",
    "Dead Bug": "Dead Bug",
    "Dead Hang": "Colgado en Barra",
    "Deadlift": "Peso Muerto",
    "Deadlift High Pull": "Peso Muerto con Tirón Alto",
    "Decline Bench Press": "Press de Banca Declinado",
    "Decline Chest Fly": "Aperturas Declinadas",
    "Decline Crunch": "Abdominal Declinado",
    "Decline Push Up": "Flexión Declinada",
    "Diamond Push Up": "Flexión Diamante",
    "Downward Dog": "Perro Boca Abajo",
    "Drag Curl": "Curl Drag",
    "Dragon Flag": "Dragon Flag",
    "Dragonfly": "Dragonfly",
    "Dumbbell Row": "Remo con Mancuerna",
    "Dumbbell Snatch": "Arranque con Mancuerna",
    "Dumbbell Squeeze Press": "Press Squeeze con Mancuernas",
    "Dumbbell Step Up": "Subida al Cajón con Mancuernas",
    "EZ Bar Biceps Curl": "Curl de Bíceps con Barra Z",
    "Elbow to Knee": "Codo a Rodilla",
    "Elliptical Trainer": "Elíptica",
    "Face Pull": "Face Pull",
    "Farmers Walk": "Caminata del Granjero",
    "Fire Hydrants": "Patada Lateral en Cuadrupedia",
    "Floor Press": "Press en el Piso",
    "Floor Triceps Dip": "Fondos de Tríceps en el Piso",
    "Flutter Kicks": "Patadas de Aleteo",
    "Frog Jumps": "Saltos de Rana",
    "Frog Pumps": "Puente de Glúteo Rana",
    "Front Lever Hold": "Front Lever Isométrico",
    "Front Lever Raise": "Elevación de Front Lever",
    "Front Raise": "Elevación Frontal",
    "Front Squat": "Sentadilla Frontal",
    "Full Squat": "Sentadilla Profunda",
    "Glute Bridge": "Puente de Glúteo",
    "Glute Ham Raise": "Elevación Femoral (GHR)",
    "Glute Kickback": "Patada de Glúteo",
    "Glute Kickback on Floor": "Patada de Glúteo en el Piso",
    "Goblet Squat": "Sentadilla Goblet",
    "Good Morning": "Buenos Días",
    "Gorilla Row": "Remo Gorila",
    "HIIT": "HIIT",
    "Hack Squat": "Sentadilla Hack",
    "Hammer Curl": "Curl Martillo",
    "Handstand Hold": "Parada de Manos Isométrica",
    "Handstand Push Up": "Flexión en Parada de Manos",
    "Hang Clean": "Cargada desde Suspensión",
    "Hang Snatch": "Arranque desde Suspensión",
    "Hanging Knee Raise": "Elevación de Rodillas Colgado",
    "Hanging Leg Raise": "Elevación de Piernas Colgado",
    "Heel Taps": "Toques de Talón",
    "Hex Press": "Press Hex",
    "High Knee Skips": "Skipping con Rodillas Altas",
    "High Knees": "Rodillas Altas",
    "Hiking": "Senderismo",
    "Hip Abduction": "Abducción de Cadera",
    "Hip Adduction": "Aducción de Cadera",
    "Hip Thrust": "Empuje de Cadera",
    "Hollow Rock": "Hollow Rock",
    "Incline Bench Press": "Press de Banca Inclinado",
    "Incline Chest Fly": "Aperturas Inclinadas",
    "Incline Chest Press": "Press de Pecho Inclinado",
    "Incline Push Ups": "Flexiones Inclinadas",
    "Inverted Row": "Remo Invertido",
    "Iso-Lateral Chest Press": "Press de Pecho Iso-Lateral",
    "Iso-Lateral High Row": "Remo Alto Iso-Lateral",
    "Iso-Lateral Low Row": "Remo Bajo Iso-Lateral",
    "Iso-Lateral Row": "Remo Iso-Lateral",
    "JM Press": "Press JM",
    "Jack Knife": "Navaja",
    "Jackknife Sit Up": "Abdominal Navaja",
    "Jump Rope": "Soga",
    "Jump Shrug": "Encogimiento con Salto",
    "Jump Squat": "Sentadilla con Salto",
    "Jumping Jack": "Salto de Tijera",
    "Jumping Lunge": "Zancada con Salto",
    "Kettlebell Clean": "Cargada con Kettlebell",
    "Kettlebell Curl": "Curl con Kettlebell",
    "Kettlebell Goblet Squat": "Sentadilla Goblet con Kettlebell",
    "Kettlebell High Pull": "Tirón Alto con Kettlebell",
    "Kettlebell Shoulder Press": "Press de Hombros con Kettlebell",
    "Kettlebell Snatch": "Arranque con Kettlebell",
    "Kettlebell Swing": "Swing con Kettlebell",
    "Kettlebell Turkish Get Up": "Turkish Get Up con Kettlebell",
    "Kipping Pull Up": "Dominada Kipping",
    "Knee Raise Parallel Bars": "Elevación de Rodillas en Paralelas",
    "Kneeling Pulldown": "Jalón Arrodillado",
    "Kneeling Push Up": "Flexión de Rodillas",
    "L-Sit Hold": "L-Sit Isométrico",
    "Landmine 180": "Landmine 180",
    "Landmine Row": "Remo Landmine",
    "Landmine Squat and Press": "Sentadilla y Press Landmine",
    "Lat Pulldown": "Jalón al Pecho",
    "Lat Pulldown - Close Grip": "Jalón al Pecho Agarre Cerrado",
    "Lateral Band Walks": "Caminata Lateral con Banda",
    "Lateral Box Jump": "Salto Lateral al Cajón",
    "Lateral Leg Raises": "Elevaciones Laterales de Pierna",
    "Lateral Lunge": "Zancada Lateral",
    "Lateral Raise": "Elevaciones Laterales",
    "Lateral Squat": "Sentadilla Lateral",
    "Leg Extension": "Extensión de Cuádriceps",
    "Leg Press": "Prensa de Piernas",
    "Leg Press Horizontal": "Prensa Horizontal",
    "Leg Raise Parallel Bars": "Elevación de Piernas en Paralelas",
    "Low Cable Fly Crossovers": "Cruces en Polea Baja",
    "Low Row": "Remo Bajo",
    "Lunge": "Zancada",
    "Lying Knee Raise": "Elevación de Rodillas Acostado",
    "Lying Leg Curl": "Curl Femoral Acostado",
    "Lying Leg Raise": "Elevación de Piernas Acostado",
    "Lying Neck Curls": "Flexión de Cuello Acostado",
    "Lying Neck Extension": "Extensión de Cuello Acostado",
    "Meadows Rows": "Remo Meadows",
    "Mountain Climber": "Escalador",
    "Muscle Up": "Muscle Up",
    "Negative Pull Up": "Dominada Negativa",
    "Nordic Hamstrings Curls": "Curl Nórdico de Femoral",
    "Oblique Crunch": "Abdominal Oblicuo",
    "One Arm Push Up": "Flexión a Un Brazo",
    "Overhead Curl": "Curl por Encima de la Cabeza",
    "Overhead Dumbbell Lunge": "Zancada con Mancuerna sobre la Cabeza",
    "Overhead Press": "Press Militar",
    "Overhead Squat": "Sentadilla Overhead",
    "Pause Squat": "Sentadilla con Pausa",
    "Pendlay Row": "Remo Pendlay",
    "Pendulum Squat": "Sentadilla Pendular",
    "Pike Pushup": "Flexión Pica",
    "Pilates": "Pilates",
    "Pinwheel Curl": "Curl Pinwheel",
    "Pistol Squat": "Sentadilla Pistol",
    "Plank": "Plancha",
    "Plank Pushup": "Plancha a Flexión",
    "Plate Curl": "Curl con Disco",
    "Plate Front Raise": "Elevación Frontal con Disco",
    "Plate Press": "Press con Disco",
    "Plate Squeeze": "Press Squeeze con Disco (Svend)",
    "Power Clean": "Cargada de Potencia",
    "Power Snatch": "Arranque de Potencia",
    "Preacher Curl": "Curl en Banco Scott",
    "Press Under": "Press Under",
    "Pull Up": "Dominada",
    "Pullover": "Pullover",
    "Push Press": "Push Press",
    "Push Up": "Flexión de Brazos",
    "Push Up - Close Grip": "Flexión Agarre Cerrado",
    "Rack Pull": "Rack Pull",
    "Rear Delt Reverse Fly": "Aperturas Invertidas (Deltoides Posterior)",
    "Renegade Row": "Remo Renegado",
    "Reverse Crunch": "Abdominal Invertido",
    "Reverse Curl": "Curl Invertido",
    "Reverse Fly Single Arm": "Apertura Invertida a Un Brazo",
    "Reverse Grip Concentration Curl": "Curl Concentrado Agarre Invertido",
    "Reverse Grip Lat Pulldown": "Jalón al Pecho Agarre Supino",
    "Reverse Hyperextension": "Hiperextensión Inversa",
    "Reverse Lunge": "Zancada Hacia Atrás",
    "Reverse Plank": "Plancha Invertida",
    "Ring Dips": "Fondos en Anillas",
    "Romanian Deadlift": "Peso Muerto Rumano",
    "Rope Cable Curl": "Curl con Soga en Polea",
    "Rope Straight Arm Pulldown": "Jalón con Brazos Rectos y Soga",
    "Rowing Machine": "Máquina de Remo",
    "Running": "Correr",
    "Russian Twist": "Giro Ruso",
    "Scapular Pull Ups": "Dominadas Escapulares",
    "Seated Cable Row - Bar Grip": "Remo Sentado en Polea (Barra)",
    "Seated Cable Row - Bar Wide Grip": "Remo Sentado en Polea (Barra Ancha)",
    "Seated Cable Row - V Grip": "Remo Sentado en Polea (Agarre V)",
    "Seated Calf Raise": "Elevación de Gemelos Sentado",
    "Seated Chest Flys": "Aperturas de Pecho Sentado",
    "Seated Dip Machine": "Máquina de Fondos Sentado",
    "Seated Incline Curl": "Curl Inclinado Sentado",
    "Seated Lateral Raise": "Elevaciones Laterales Sentado",
    "Seated Leg Curl": "Curl Femoral Sentado",
    "Seated Overhead Press": "Press Militar Sentado",
    "Seated Palms Up Wrist Curl": "Curl de Muñeca Palmas Arriba Sentado",
    "Seated Row": "Remo Sentado",
    "Seated Shoulder Press": "Press de Hombros Sentado",
    "Seated Triceps Press": "Press de Tríceps Sentado",
    "Seated Wrist Extension": "Extensión de Muñeca Sentado",
    "Shoulder Press": "Press de Hombros",
    "Shoulder Taps": "Toques de Hombro",
    "Shrug": "Encogimiento de Hombros",
    "Side Bend": "Flexión Lateral de Tronco",
    "Side Plank": "Plancha Lateral",
    "Single Arm Cable Crossover": "Cruce en Polea a Un Brazo",
    "Single Arm Cable Row": "Remo en Polea a Un Brazo",
    "Single Arm Curl": "Curl a Un Brazo",
    "Single Arm Landmine Press": "Press Landmine a Un Brazo",
    "Single Arm Lat Pulldown": "Jalón al Pecho a Un Brazo",
    "Single Arm Lateral Raise": "Elevación Lateral a Un Brazo",
    "Single Arm Tricep Extension": "Extensión de Tríceps a Un Brazo",
    "Single Arm Triceps Pushdown": "Extensión de Tríceps en Polea a Un Brazo",
    "Single Leg Extensions": "Extensión de Cuádriceps a Una Pierna",
    "Single Leg Glute Bridge": "Puente de Glúteo a Una Pierna",
    "Single Leg Hip Thrust": "Empuje de Cadera a Una Pierna",
    "Single Leg Press": "Prensa a Una Pierna",
    "Single Leg Romanian Deadlift": "Peso Muerto Rumano a Una Pierna",
    "Single Leg Standing Calf Raise": "Elevación de Gemelo a Una Pierna de Pie",
    "Sissy Squat": "Sentadilla Sissy",
    "Sit Up": "Abdominal Completo",
    "Skating": "Patinaje",
    "Skiing": "Esquí",
    "Skullcrusher": "Press Francés",
    "Sled Push": "Empuje de Trineo",
    "Snatch": "Arranque",
    "Snowboarding": "Snowboard",
    "Spider Curl": "Curl Spider",
    "Spiderman": "Plancha Spiderman",
    "Spinning": "Spinning",
    "Split Jerk": "Envión en Tijera",
    "Split Squat": "Sentadilla Split",
    "Sprints": "Sprints",
    "Squat": "Sentadilla",
    "Squat Row": "Sentadilla con Remo",
    "Stair Machine": "Máquina Escaladora",
    "Standing Cable Glute Kickbacks": "Patada de Glúteo en Polea de Pie",
    "Standing Calf Raise": "Elevación de Gemelos de Pie",
    "Standing Leg Curls": "Curl Femoral de Pie",
    "Standing Military Press": "Press Militar de Pie",
    "Step Up": "Subida al Cajón",
    "Sternum Pull up": "Dominada al Esternón (Gironda)",
    "Straight Arm Lat Pulldown": "Jalón con Brazos Rectos",
    "Straight Leg Deadlift": "Peso Muerto con Piernas Rectas",
    "Sumo Deadlift": "Peso Muerto Sumo",
    "Sumo Squat": "Sentadilla Sumo",
    "Superman": "Superman",
    "Swimming": "Natación",
    "T Bar Row": "Remo en Barra T",
    "Thruster": "Thruster",
    "Toe Touch": "Toque de Puntas",
    "Toes to Bar": "Puntas a la Barra",
    "Torso Rotation": "Rotación de Tronco",
    "Treadmill": "Cinta",
    "Triceps Dip": "Fondos de Tríceps",
    "Triceps Extension": "Extensión de Tríceps",
    "Triceps Kickback": "Patada de Tríceps",
    "Triceps Pressdown": "Extensión de Tríceps en Polea",
    "Triceps Pushdown": "Extensión de Tríceps en Polea",
    "Triceps Rope Pushdown": "Extensión de Tríceps con Soga",
    "Upright Row": "Remo al Mentón",
    "V Up": "Abdominal en V",
    "Walking": "Caminar",
    "Walking Lunge": "Zancada Caminando",
    "Wall Ball": "Wall Ball",
    "Wall Sit": "Sentadilla Isométrica en Pared",
    "Warm Up": "Entrada en Calor",
    "Wide Pull Up": "Dominada Agarre Ancho",
    "Wrist Roller": "Enrollador de Muñeca",
    "Yoga": "Yoga",
    "Zercher Squat": "Sentadilla Zercher",
    "Zottman Curl": "Curl Zottman",
}

def split(name):
    m = re.search(r'\s*\(([^)]*)\)\s*$', name)
    if m:
        return name[:m.start()].strip(), m.group(1).strip()
    return name.strip(), None

missing = []
out = {}
for r in cat:
    en = r['name']
    base, paren = split(en)
    es_base = BASE.get(base)
    if es_base is None:
        missing.append(base)
        es = en
    elif paren:
        es_paren = EQUIP.get(paren, paren)
        es = f"{es_base} ({es_paren})"
    else:
        es = es_base
    out[r['id']] = {"es": es, "en": en}

json.dump(out, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("nombres:", len(out), "| bases sin traducir:", len(set(missing)))
for b in sorted(set(missing)): print("  MISSING:", b)
# muestra
for i in ["hevy-bench-press-barbell","hevy-squat-dumbbell","hevy-cable-twist-down-to-up","hevy-shrug-cable"]:
    print(" ", i, "->", out[i]['es'])
